# # tts_service.py
# from io import BytesIO
# from gtts import gTTS
# from langdetect import detect, LangDetectException

# SUPPORTED = {"fr", "en", "ar", "es", "de", "it", "pt"}

# def detect_language(text: str, fallback: str = "en") -> str:
#     try:
#         lang = detect(text)
#         return lang if lang in SUPPORTED else fallback
#     except LangDetectException:
#         return fallback

# def tts_gtts(text: str, lang: str) -> bytes:
#     """
#     Returns MP3 bytes generated by gTTS.
#     """
#     tts = gTTS(text=text, lang=lang)
#     buf = BytesIO()
#     tts.write_to_fp(buf)
#     return buf.getvalue()



# tts_service_edge.py
import asyncio
from io import BytesIO
import edge_tts
from langdetect import detect, LangDetectException




# (langue, genre)  →  voix Microsoft Edge TTS
VOICE_MAP = {
    ("fr", "Female"): "fr-FR-DeniseNeural",
    ("fr", "Male"):   "fr-FR-HenriNeural",
    ("en", "Female"): "en-US-JennyNeural",
    ("en", "Male"):   "en-US-GuyNeural",
    ("ar", "Female"): "ar-SA-ZariyahNeural",
    ("ar", "Male"):   "ar-SA-HamedNeural",
}




# Edge TTS signifie Text-To-Speech de Microsoft Edge.
# C’est un moteur qui transforme du texte → voix naturelle IA
def tts_edge(text: str, lang: str, voice: str, speed: float = 1.0) -> bytes:
    voice_id = VOICE_MAP.get((lang, voice), VOICE_MAP.get((lang, "Female")))

    # Convert speed (1.0 = normal)
    rate_pct = int((speed - 1.0) * 100)
    rate_str = f"{rate_pct:+d}%"

    async def _run():
        output = BytesIO()
        communicate = edge_tts.Communicate(
            text=text,
            voice=voice_id,
            rate=rate_str
        )
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                output.write(chunk["data"])
        return output.getvalue()

    return asyncio.run(_run())
SUPPORTED = {"fr", "en", "ar", "es", "de", "it", "pt"}

def detect_language(text: str, fallback: str = "en") -> str:
    try:
        lang = detect(text)
        return lang if lang in SUPPORTED else fallback
    except LangDetectException:
        return fallback
